### ISSUE TITLE
Error Creating Conversations Client

### ISSUE THREAD

**Issue by EMChamp** [TwilioDevEd/conversations-quickstart-android#9]
Issue:
Cannot create a Conversations Client

Steps Taken:
-Build Project on Android Studio 4.1
-Generate Access Token in Twilio CLI
-Input access token in strings.xml
-Run on Android Simulator
-Try to send message

Error Messages Seen:
2021-05-27 17:35:49.518 8843-8843/com.twilio.conversationsquickstart E/emchamptag: Error creating Twilio Conversations Client: Command timeout reached

Full Run Log is attached

[error_conversations.txt](https://github.com/TwilioDevEd/conversations-quickstart-android/files/6552828/error_conversations.txt)

**Comment by jefflinwood** [comment]
Hi,

I just tried to repeat this (but using a physical Android device). 

I was able to replicate the Command timeout reached issue when putting the device into airplane mode, or putting in a completely invalid access token, such as "Testing" (no quotes). I suspect the issue may be the access token.

**Comment by EMChamp** [comment]
Hi @jefflinwood thanks for the help on this. As you pointed out, the error was due to an invalid access token.
